const DICTIONARY = [
  // === Sapaan & Umum ===
  { ar: "السَّلَامُ عَلَيْكُمْ", tr: "as-salāmu 'alaikum", id: "Semoga keselamatan atasmu", cat: "Sapaan", ex_ar: "السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللهِ", ex_id: "Semoga keselamatan dan rahmat Allah atasmu" },
  { ar: "شُكْرًا", tr: "syukran", id: "Terima kasih", cat: "Sapaan", ex_ar: "شُكْرًا جَزِيلًا", ex_id: "Terima kasih banyak" },
  { ar: "عَفْوًا", tr: "'afwan", id: "Maaf / Sama-sama", cat: "Sapaan", ex_ar: "عَفْوًا، أَيْنَ المَسْجِدُ؟", ex_id: "Maaf, di mana masjid?" },
  { ar: "مَرْحَبًا", tr: "marhaban", id: "Selamat datang", cat: "Sapaan", ex_ar: "مَرْحَبًا بِكُمْ", ex_id: "Selamat datang (untuk kalian)" },
  { ar: "صَبَاحُ الخَيْرِ", tr: "ṣabāḥul khair", id: "Selamat pagi", cat: "Sapaan", ex_ar: "صَبَاحُ الخَيْرِ يَا أُسْتَاذ", ex_id: "Selamat pagi, Pak Guru" },
  { ar: "مَسَاءُ الخَيْرِ", tr: "masā'ul khair", id: "Selamat sore/malam", cat: "Sapaan", ex_ar: "مَسَاءُ الخَيْرِ يَا صَدِيقِي", ex_id: "Selamat sore, temanku" },
  { ar: "كَيْفَ حَالُكَ", tr: "kaifa ḥāluka", id: "Apa kabarmu?", cat: "Sapaan", ex_ar: "كَيْفَ حَالُكَ اليَوْمَ؟", ex_id: "Apa kabarmu hari ini?" },
  { ar: "نَعَمْ", tr: "na'am", id: "Ya", cat: "Sapaan" },
  { ar: "لَا", tr: "lā", id: "Tidak", cat: "Sapaan" },
  { ar: "مِنْ فَضْلِكَ", tr: "min faḍlika", id: "Tolong / Silakan", cat: "Sapaan" },

  // === Keluarga ===
  { ar: "أَبٌ", tr: "abun", id: "Ayah", cat: "Keluarga", ex_ar: "أَبِي مُعَلِّمٌ", ex_id: "Ayahku seorang guru" },
  { ar: "أُمٌّ", tr: "ummun", id: "Ibu", cat: "Keluarga", ex_ar: "أُمِّي طَبِيبَةٌ", ex_id: "Ibuku seorang dokter" },
  { ar: "أَخٌ", tr: "akhun", id: "Saudara laki-laki", cat: "Keluarga", ex_ar: "عِنْدِي أَخٌ وَاحِدٌ", ex_id: "Saya punya satu saudara laki-laki" },
  { ar: "أُخْتٌ", tr: "ukhtun", id: "Saudara perempuan", cat: "Keluarga", ex_ar: "أُخْتِي فِي المَدْرَسَةِ", ex_id: "Saudara perempuanku di sekolah" },
  { ar: "جَدٌّ", tr: "jaddun", id: "Kakek", cat: "Keluarga" },
  { ar: "جَدَّةٌ", tr: "jaddatun", id: "Nenek", cat: "Keluarga" },
  { ar: "اِبْنٌ", tr: "ibnun", id: "Anak laki-laki", cat: "Keluarga", ex_ar: "هَذَا اِبْنِي", ex_id: "Ini anak laki-lakiku" },
  { ar: "بِنْتٌ", tr: "bintun", id: "Anak perempuan", cat: "Keluarga", ex_ar: "هَذِهِ بِنْتِي", ex_id: "Ini anak perempuanku" },
  { ar: "عَائِلَةٌ", tr: "'ā'ilatun", id: "Keluarga", cat: "Keluarga", ex_ar: "عَائِلَتِي كَبِيرَةٌ", ex_id: "Keluargaku besar" },
  { ar: "زَوْجٌ", tr: "zaujun", id: "Suami", cat: "Keluarga" },
  { ar: "زَوْجَةٌ", tr: "zaujatun", id: "Istri", cat: "Keluarga" },
  { ar: "عَمٌّ", tr: "'ammun", id: "Paman (dari ayah)", cat: "Keluarga" },
  { ar: "خَالٌ", tr: "khālun", id: "Paman (dari ibu)", cat: "Keluarga" },

  // === Sekolah ===
  { ar: "مَدْرَسَةٌ", tr: "madrasatun", id: "Sekolah", cat: "Sekolah", ex_ar: "المَدْرَسَةُ قَرِيبَةٌ", ex_id: "Sekolahnya dekat" },
  { ar: "كِتَابٌ", tr: "kitābun", id: "Buku", cat: "Sekolah", ex_ar: "هَذَا كِتَابٌ جَدِيدٌ", ex_id: "Ini buku baru" },
  { ar: "قَلَمٌ", tr: "qalamun", id: "Pena", cat: "Sekolah", ex_ar: "أَعْطِنِي قَلَمًا", ex_id: "Berikan saya pena" },
  { ar: "مُعَلِّمٌ", tr: "mu'allimun", id: "Guru (laki-laki)", cat: "Sekolah", ex_ar: "المُعَلِّمُ فِي الفَصْلِ", ex_id: "Guru di dalam kelas" },
  { ar: "مُعَلِّمَةٌ", tr: "mu'allimatun", id: "Guru (perempuan)", cat: "Sekolah" },
  { ar: "طَالِبٌ", tr: "ṭālibun", id: "Siswa / Pelajar", cat: "Sekolah", ex_ar: "أَنَا طَالِبٌ جَدِيدٌ", ex_id: "Saya siswa baru" },
  { ar: "فَصْلٌ", tr: "faṣlun", id: "Kelas", cat: "Sekolah" },
  { ar: "دَفْتَرٌ", tr: "daftarun", id: "Buku tulis", cat: "Sekolah" },
  { ar: "سَبُّورَةٌ", tr: "sabbūratun", id: "Papan tulis", cat: "Sekolah" },
  { ar: "كُرْسِيٌّ", tr: "kursiyyun", id: "Kursi", cat: "Sekolah" },
  { ar: "مَكْتَبٌ", tr: "maktabun", id: "Meja / Kantor", cat: "Sekolah" },
  { ar: "حَقِيبَةٌ", tr: "ḥaqībatun", id: "Tas", cat: "Sekolah" },
  { ar: "اِمْتِحَانٌ", tr: "imtiḥānun", id: "Ujian", cat: "Sekolah" },
  { ar: "وَاجِبٌ", tr: "wājibun", id: "Tugas / PR", cat: "Sekolah" },
  { ar: "دَرْسٌ", tr: "darsun", id: "Pelajaran", cat: "Sekolah" },

  // === Makanan & Minuman ===
  { ar: "مَاءٌ", tr: "mā'un", id: "Air", cat: "Makanan", ex_ar: "أُرِيدُ مَاءً بَارِدًا", ex_id: "Saya mau air dingin" },
  { ar: "خُبْزٌ", tr: "khubzun", id: "Roti", cat: "Makanan", ex_ar: "الخُبْزُ طَازَجٌ", ex_id: "Rotinya segar" },
  { ar: "أَرُزٌّ", tr: "aruzzun", id: "Nasi", cat: "Makanan", ex_ar: "أُحِبُّ الأَرُزَّ", ex_id: "Saya suka nasi" },
  { ar: "لَحْمٌ", tr: "laḥmun", id: "Daging", cat: "Makanan" },
  { ar: "سَمَكٌ", tr: "samakun", id: "Ikan", cat: "Makanan" },
  { ar: "دَجَاجٌ", tr: "dajājun", id: "Ayam", cat: "Makanan" },
  { ar: "فَاكِهَةٌ", tr: "fākihatun", id: "Buah-buahan", cat: "Makanan" },
  { ar: "تُفَّاحَةٌ", tr: "tuffāḥatun", id: "Apel", cat: "Makanan" },
  { ar: "مَوْزٌ", tr: "mauzun", id: "Pisang", cat: "Makanan" },
  { ar: "حَلِيبٌ", tr: "ḥalībun", id: "Susu", cat: "Makanan", ex_ar: "أَشْرَبُ الحَلِيبَ كُلَّ يَوْمٍ", ex_id: "Saya minum susu setiap hari" },
  { ar: "شَايٌ", tr: "syāyun", id: "Teh", cat: "Makanan" },
  { ar: "قَهْوَةٌ", tr: "qahwatun", id: "Kopi", cat: "Makanan" },
  { ar: "سُكَّرٌ", tr: "sukkarun", id: "Gula", cat: "Makanan" },
  { ar: "مِلْحٌ", tr: "milḥun", id: "Garam", cat: "Makanan" },
  { ar: "بَيْضٌ", tr: "baiḍun", id: "Telur", cat: "Makanan" },
  { ar: "خُضَرٌ", tr: "khuḍarun", id: "Sayuran", cat: "Makanan" },

  // === Tempat ===
  { ar: "بَيْتٌ", tr: "baitun", id: "Rumah", cat: "Tempat", ex_ar: "بَيْتِي كَبِيرٌ", ex_id: "Rumahku besar" },
  { ar: "مَسْجِدٌ", tr: "masjidun", id: "Masjid", cat: "Tempat", ex_ar: "المَسْجِدُ قَرِيبٌ مِنْ هُنَا", ex_id: "Masjidnya dekat dari sini" },
  { ar: "سُوقٌ", tr: "sūqun", id: "Pasar", cat: "Tempat", ex_ar: "ذَهَبْتُ إِلَى السُّوقِ", ex_id: "Saya pergi ke pasar" },
  { ar: "مُسْتَشْفَى", tr: "mustasyfā", id: "Rumah sakit", cat: "Tempat" },
  { ar: "مَكْتَبَةٌ", tr: "maktabatun", id: "Perpustakaan", cat: "Tempat" },
  { ar: "مَطَارٌ", tr: "maṭārun", id: "Bandara", cat: "Tempat" },
  { ar: "شَارِعٌ", tr: "syāri'un", id: "Jalan", cat: "Tempat" },
  { ar: "حَدِيقَةٌ", tr: "ḥadīqatun", id: "Taman", cat: "Tempat" },
  { ar: "مَطْعَمٌ", tr: "maṭ'amun", id: "Restoran", cat: "Tempat" },
  { ar: "مَحَطَّةٌ", tr: "maḥaṭṭatun", id: "Stasiun", cat: "Tempat" },

  // === Waktu ===
  { ar: "يَوْمٌ", tr: "yaumun", id: "Hari", cat: "Waktu", ex_ar: "اليَوْمُ يَوْمُ الجُمُعَةِ", ex_id: "Hari ini hari Jumat" },
  { ar: "أُسْبُوعٌ", tr: "usbū'un", id: "Minggu", cat: "Waktu" },
  { ar: "شَهْرٌ", tr: "syahrun", id: "Bulan", cat: "Waktu" },
  { ar: "سَنَةٌ", tr: "sanatun", id: "Tahun", cat: "Waktu" },
  { ar: "سَاعَةٌ", tr: "sā'atun", id: "Jam", cat: "Waktu", ex_ar: "السَّاعَةُ الثَّالِثَةُ", ex_id: "Jam tiga" },
  { ar: "دَقِيقَةٌ", tr: "daqīqatun", id: "Menit", cat: "Waktu" },
  { ar: "صَبَاحٌ", tr: "ṣabāḥun", id: "Pagi", cat: "Waktu" },
  { ar: "مَسَاءٌ", tr: "masā'un", id: "Sore / Malam", cat: "Waktu" },
  { ar: "اللَّيْلُ", tr: "al-lailu", id: "Malam", cat: "Waktu" },
  { ar: "الآنَ", tr: "al-āna", id: "Sekarang", cat: "Waktu" },
  { ar: "غَدًا", tr: "ghadan", id: "Besok", cat: "Waktu" },
  { ar: "أَمْسِ", tr: "amsi", id: "Kemarin", cat: "Waktu" },

  // === Kata Sifat ===
  { ar: "كَبِيرٌ", tr: "kabīrun", id: "Besar", cat: "Sifat", ex_ar: "البَيْتُ كَبِيرٌ", ex_id: "Rumah itu besar" },
  { ar: "صَغِيرٌ", tr: "ṣaghīrun", id: "Kecil", cat: "Sifat", ex_ar: "الكِتَابُ صَغِيرٌ", ex_id: "Buku itu kecil" },
  { ar: "جَمِيلٌ", tr: "jamīlun", id: "Indah / Cantik", cat: "Sifat", ex_ar: "المَدِينَةُ جَمِيلَةٌ", ex_id: "Kotanya indah" },
  { ar: "جَدِيدٌ", tr: "jadīdun", id: "Baru", cat: "Sifat" },
  { ar: "قَدِيمٌ", tr: "qadīmun", id: "Lama / Tua", cat: "Sifat" },
  { ar: "سَهْلٌ", tr: "sahlun", id: "Mudah", cat: "Sifat" },
  { ar: "صَعْبٌ", tr: "ṣa'bun", id: "Sulit", cat: "Sifat" },
  { ar: "بَارِدٌ", tr: "bāridun", id: "Dingin", cat: "Sifat" },
  { ar: "حَارٌّ", tr: "ḥārrun", id: "Panas", cat: "Sifat" },
  { ar: "قَرِيبٌ", tr: "qarībun", id: "Dekat", cat: "Sifat" },
  { ar: "بَعِيدٌ", tr: "ba'īdun", id: "Jauh", cat: "Sifat" },
  { ar: "طَوِيلٌ", tr: "ṭawīlun", id: "Panjang / Tinggi", cat: "Sifat" },
  { ar: "قَصِيرٌ", tr: "qaṣīrun", id: "Pendek", cat: "Sifat" },
  { ar: "نَظِيفٌ", tr: "naẓīfun", id: "Bersih", cat: "Sifat" },
  { ar: "سَرِيعٌ", tr: "sarī'un", id: "Cepat", cat: "Sifat" },

  // === Kata Kerja (Madhi - Mudhore' - Masdar) ===
  { madhi: "ذَهَبَ", mudhore: "يَذْهَبُ", masdar: "ذَهَابًا", tr: "żahaba - yażhabu - żahāban", id: "Pergi", cat: "Kata Kerja", ex_ar: "ذَهَبَ إِلَى المَدْرَسَةِ", ex_id: "Dia pergi ke sekolah" },
  { madhi: "جَلَسَ", mudhore: "يَجْلِسُ", masdar: "جُلُوسًا", tr: "jalasa - yajlisu - julūsan", id: "Duduk", cat: "Kata Kerja", ex_ar: "جَلَسَ عَلَى الكُرْسِيِّ", ex_id: "Dia duduk di kursi" },
  { madhi: "كَتَبَ", mudhore: "يَكْتُبُ", masdar: "كِتَابَةً", tr: "kataba - yaktubu - kitābatan", id: "Menulis", cat: "Kata Kerja", ex_ar: "كَتَبَ الدَّرْسَ", ex_id: "Dia menulis pelajaran" },
  { madhi: "قَرَأَ", mudhore: "يَقْرَأُ", masdar: "قِرَاءَةً", tr: "qara'a - yaqra'u - qirā'atan", id: "Membaca", cat: "Kata Kerja", ex_ar: "قَرَأَ القُرْآنَ", ex_id: "Dia membaca Al-Quran" },
  { madhi: "أَكَلَ", mudhore: "يَأْكُلُ", masdar: "أَكْلًا", tr: "akala - ya'kulu - aklan", id: "Makan", cat: "Kata Kerja", ex_ar: "أَكَلَ الأَرُزَّ", ex_id: "Dia makan nasi" },
  { madhi: "شَرِبَ", mudhore: "يَشْرَبُ", masdar: "شُرْبًا", tr: "syariba - yasyrabu - syurban", id: "Minum", cat: "Kata Kerja" },
  { madhi: "نَامَ", mudhore: "يَنَامُ", masdar: "نَوْمًا", tr: "nāma - yanāmu - nauman", id: "Tidur", cat: "Kata Kerja" },
  { madhi: "فَتَحَ", mudhore: "يَفْتَحُ", masdar: "فَتْحًا", tr: "fataḥa - yaftaḥu - fatḥan", id: "Membuka", cat: "Kata Kerja" },
  { madhi: "أَغْلَقَ", mudhore: "يُغْلِقُ", masdar: "إِغْلَاقًا", tr: "aghlaqa - yughliqu - ighlāqan", id: "Menutup", cat: "Kata Kerja" },
  { madhi: "سَمِعَ", mudhore: "يَسْمَعُ", masdar: "سَمْعًا", tr: "sami'a - yasma'u - sam'an", id: "Mendengar", cat: "Kata Kerja" },
  { madhi: "نَظَرَ", mudhore: "يَنْظُرُ", masdar: "نَظَرًا", tr: "naẓara - yanẓuru - naẓaran", id: "Melihat", cat: "Kata Kerja" },
  { madhi: "عَمِلَ", mudhore: "يَعْمَلُ", masdar: "عَمَلًا", tr: "'amila - ya'malu - 'amalan", id: "Bekerja", cat: "Kata Kerja" },
  { madhi: "دَرَسَ", mudhore: "يَدْرُسُ", masdar: "دِرَاسَةً", tr: "darasa - yadrusu - dirāsatan", id: "Belajar", cat: "Kata Kerja", ex_ar: "دَرَسَ اللُّغَةَ العَرَبِيَّةَ", ex_id: "Dia belajar bahasa Arab" },
  { madhi: "سَأَلَ", mudhore: "يَسْأَلُ", masdar: "سُؤَالًا", tr: "sa'ala - yas'alu - su'ālan", id: "Bertanya", cat: "Kata Kerja" },
  { madhi: "أَجَابَ", mudhore: "يُجِيبُ", masdar: "إِجَابَةً", tr: "ajāba - yujību - ijābatan", id: "Menjawab", cat: "Kata Kerja" },

  // === Angka ===
  { ar: "وَاحِدٌ", tr: "wāḥidun", id: "Satu (1)", cat: "Angka" },
  { ar: "اِثْنَانِ", tr: "itsnāni", id: "Dua (2)", cat: "Angka" },
  { ar: "ثَلَاثَةٌ", tr: "tsalātsatun", id: "Tiga (3)", cat: "Angka" },
  { ar: "أَرْبَعَةٌ", tr: "arba'atun", id: "Empat (4)", cat: "Angka" },
  { ar: "خَمْسَةٌ", tr: "khamsatun", id: "Lima (5)", cat: "Angka" },
  { ar: "سِتَّةٌ", tr: "sittatun", id: "Enam (6)", cat: "Angka" },
  { ar: "سَبْعَةٌ", tr: "sab'atun", id: "Tujuh (7)", cat: "Angka" },
  { ar: "ثَمَانِيَةٌ", tr: "tsamāniyatun", id: "Delapan (8)", cat: "Angka" },
  { ar: "تِسْعَةٌ", tr: "tis'atun", id: "Sembilan (9)", cat: "Angka" },
  { ar: "عَشَرَةٌ", tr: "'asyaratun", id: "Sepuluh (10)", cat: "Angka" },
  { ar: "مِائَةٌ", tr: "mi'atun", id: "Seratus (100)", cat: "Angka" },
  { ar: "أَلْفٌ", tr: "alfun", id: "Seribu (1000)", cat: "Angka" },

  // === Warna ===
  { ar: "أَبْيَضُ", tr: "abyaḍu", id: "Putih", cat: "Warna" },
  { ar: "أَسْوَدُ", tr: "aswadu", id: "Hitam", cat: "Warna" },
  { ar: "أَحْمَرُ", tr: "aḥmaru", id: "Merah", cat: "Warna" },
  { ar: "أَزْرَقُ", tr: "azraqu", id: "Biru", cat: "Warna" },
  { ar: "أَخْضَرُ", tr: "akhḍaru", id: "Hijau", cat: "Warna" },
  { ar: "أَصْفَرُ", tr: "aṣfaru", id: "Kuning", cat: "Warna" },

  // === Alam ===
  { ar: "شَمْسٌ", tr: "syamsun", id: "Matahari", cat: "Alam", ex_ar: "الشَّمْسُ سَاطِعَةٌ", ex_id: "Matahari bersinar terang" },
  { ar: "قَمَرٌ", tr: "qamarun", id: "Bulan (di langit)", cat: "Alam" },
  { ar: "نَجْمٌ", tr: "najmun", id: "Bintang", cat: "Alam" },
  { ar: "سَمَاءٌ", tr: "samā'un", id: "Langit", cat: "Alam" },
  { ar: "أَرْضٌ", tr: "arḍun", id: "Bumi / Tanah", cat: "Alam" },
  { ar: "بَحْرٌ", tr: "baḥrun", id: "Laut", cat: "Alam" },
  { ar: "نَهْرٌ", tr: "nahrun", id: "Sungai", cat: "Alam" },
  { ar: "جَبَلٌ", tr: "jabalun", id: "Gunung", cat: "Alam" },
  { ar: "شَجَرَةٌ", tr: "syajaratun", id: "Pohon", cat: "Alam" },
  { ar: "زَهْرَةٌ", tr: "zahratun", id: "Bunga", cat: "Alam" },
  { ar: "مَطَرٌ", tr: "maṭarun", id: "Hujan", cat: "Alam" },
  { ar: "رِيحٌ", tr: "rīḥun", id: "Angin", cat: "Alam" },

  // === Tubuh ===
  { ar: "رَأْسٌ", tr: "ra'sun", id: "Kepala", cat: "Tubuh" },
  { ar: "عَيْنٌ", tr: "'ainun", id: "Mata", cat: "Tubuh" },
  { ar: "أُذُنٌ", tr: "użunun", id: "Telinga", cat: "Tubuh" },
  { ar: "أَنْفٌ", tr: "anfun", id: "Hidung", cat: "Tubuh" },
  { ar: "فَمٌ", tr: "famun", id: "Mulut", cat: "Tubuh" },
  { ar: "يَدٌ", tr: "yadun", id: "Tangan", cat: "Tubuh" },
  { ar: "رِجْلٌ", tr: "rijlun", id: "Kaki", cat: "Tubuh" },
  { ar: "قَلْبٌ", tr: "qalbun", id: "Hati / Jantung", cat: "Tubuh", ex_ar: "قَلْبُهُ طَيِّبٌ", ex_id: "Hatinya baik" },

  // === Agama ===
  { ar: "صَلَاةٌ", tr: "ṣalātun", id: "Shalat", cat: "Agama", ex_ar: "أَقِمِ الصَّلَاةَ", ex_id: "Dirikanlah shalat" },
  { ar: "صِيَامٌ", tr: "ṣiyāmun", id: "Puasa", cat: "Agama" },
  { ar: "زَكَاةٌ", tr: "zakātun", id: "Zakat", cat: "Agama" },
  { ar: "حَجٌّ", tr: "ḥajjun", id: "Haji", cat: "Agama" },
  { ar: "دُعَاءٌ", tr: "du'ā'un", id: "Doa", cat: "Agama", ex_ar: "اَللّٰهُمَّ اسْتَجِبْ دُعَاءَنَا", ex_id: "Ya Allah, kabulkanlah doa kami" },
  { ar: "قُرْآنٌ", tr: "qur'ānun", id: "Al-Quran", cat: "Agama" },
  { ar: "مُسْلِمٌ", tr: "muslimun", id: "Muslim", cat: "Agama" },
  { ar: "إِيمَانٌ", tr: "īmānun", id: "Iman", cat: "Agama" },
  { ar: "تَوْبَةٌ", tr: "taubatun", id: "Taubat", cat: "Agama" },
  { ar: "رَمَضَانُ", tr: "ramaḍānu", id: "Ramadhan", cat: "Agama" },

  { ar: "بَابٌ", tr: "baabun", id: "Pintu" },

];
